<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AtlasDrop.Core\AtlasDrop.Core.csproj" />
    <ProjectReference Include="..\AtlasDrop.Infrastructure\AtlasDrop.Infrastructure.csproj" />
  </ItemGroup>
</Project>
